option('log_level', type: 'combo', choices: ['traceL3', 'traceL2', 'traceL1', 'debug', 'info', 'warning', 'error', 'critial'], value: 'info', description: 'Set the log level for the GridFire library')
option('pkg_config', type: 'boolean', value: true, description: 'generate pkg-config file for GridFire (gridfire.pc)')
option('build_python', type: 'boolean', value: false, description: 'build the python bindings so you can use GridFire from python')
option('build_tests', type: 'boolean', value: true, description: 'build the test suite')
option('build_examples', type: 'boolean', value: true, description: 'build example code')
option('build_fortran', type: 'boolean', value: false, description: 'build fortran module support')
option('unsafe_fortran', type: 'boolean', value: false, description: 'Allow untested fortran compilers (compilers other than gfortran)')
option('plugin_support', type: 'boolean', value: false, description: 'Enable support for libplugin plugins')
option('python_target_version', type: 'string', value: '3.13', description: 'Target version for python compilation, only used for cross compilation')
option('build_c_api', type: 'boolean', value: true, description: 'compile the C API')
