[build-system]
requires = ["meson-python>=0.19.0", "meson>=1.9.1", "pybind11==3.0.0", "fourdst==0.10.5"]
build-backend = "mesonpy"

[project]
name = "gridfire"
dynamic = ["version"]
description = "Python interface to the GridFire nuclear network code"
readme = "README.md"
license = { file = "LICENSE.txt" }

authors = [
    {name = "Emily M. Boudreaux", email = "emily@boudreauxmail.com"},
    {name = "Aaron Dotter", email = "aaron.dotter@gmail.com"}
]
maintainers = [
    {name = "Emily M. Boudreaux", email = "emily@boudreauxmail.com"}
]

dependencies = ["fourdst==0.10.5"]

[tool.meson-python.args]
setup = [
    '-Ddefault_library=static',
    '-Dpkg_config=false',
    '-Dbuildtype=release',
    '-Dopenmp_support=true',
    '-Dasan=false',
    '-Dlog_level=error',
    '-Dbuild_tests=false',
    '-Dbuild_c_api=false',
    '-Dbuild_examples=false',
    '-Dbuild_benchmarks=false',
    '-Dbuild_tools=false',
    '-Dplugin_support=false',
    '-Duse_mimalloc=false',
    '-Dbuild_python=true'
]
install = ['--skip-subprojects']
